#pragma once

#define MAIN_Version "30ff6c7"
#define KNX_Version "2.3.1+7124a64"
#define MODULE_AccessControl_Version "0.14.0+1c5ffd5"
#define MODULE_AccessControl_Version_Major 0
#define MODULE_AccessControl_Version_Minor 14
#define MODULE_AccessControl_Version_Revision 0
#define MODULE_AccessControl_ETS 14
#define MODULE_Feedback_Version "0.3.3+2319e36"
#define MODULE_Feedback_Version_Major 0
#define MODULE_Feedback_Version_Minor 3
#define MODULE_Feedback_Version_Revision 3
#define MODULE_Feedback_ETS 3
#define MODULE_Common_Version "1.8.1+f6dbb3c"
#define MODULE_Common_Version_Major 1
#define MODULE_Common_Version_Minor 8
#define MODULE_Common_Version_Revision 1
#define MODULE_Common_ETS 24
#define MODULE_LogicModule_Version "4.3.0+8c0d835"
#define MODULE_LogicModule_Version_Major 4
#define MODULE_LogicModule_Version_Minor 3
#define MODULE_LogicModule_Version_Revision 0
#define MODULE_LogicModule_ETS 67
#define MODULE_FileTransferModule_Version "0.1.5+178f186"
#define MODULE_FileTransferModule_Version_Major 0
#define MODULE_FileTransferModule_Version_Minor 1
#define MODULE_FileTransferModule_Version_Revision 5
#define MODULE_FileTransferModule_ETS 1
#define MODULE_BinaryInput_Version "0.3.1+19e648c"
#define MODULE_BinaryInput_Version_Major 0
#define MODULE_BinaryInput_Version_Minor 3
#define MODULE_BinaryInput_Version_Revision 1
#define MODULE_BinaryInput_ETS 3
#define MODULE_SwitchActuator_Version "0.3.0+628478e"
#define MODULE_SwitchActuator_Version_Major 0
#define MODULE_SwitchActuator_Version_Minor 3
#define MODULE_SwitchActuator_Version_Revision 0
#define MODULE_SwitchActuator_ETS 3
#define MODULE_VirtualButton_Version "0.6.0+9ea99b5"
#define MODULE_VirtualButton_Version_Major 0
#define MODULE_VirtualButton_Version_Minor 6
#define MODULE_VirtualButton_Version_Revision 0
#define MODULE_VirtualButton_ETS 6
